# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1139, 947)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PlotRegion = MplWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlotRegion.sizePolicy().hasHeightForWidth())
        self.PlotRegion.setSizePolicy(sizePolicy)
        self.PlotRegion.setObjectName("PlotRegion")
        self.horizontalLayout_3.addWidget(self.PlotRegion)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.globalNormLabel = QtWidgets.QLabel(self.centralwidget)
        self.globalNormLabel.setObjectName("globalNormLabel")
        self.horizontalLayout.addWidget(self.globalNormLabel)
        self.globalNormCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.globalNormCheckBox.setMouseTracking(False)
        self.globalNormCheckBox.setChecked(False)
        self.globalNormCheckBox.setObjectName("globalNormCheckBox")
        self.horizontalLayout.addWidget(self.globalNormCheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.freqminLabel = QtWidgets.QLabel(self.centralwidget)
        self.freqminLabel.setObjectName("freqminLabel")
        self.verticalLayout.addWidget(self.freqminLabel)
        self.FreqMinSlider = QtWidgets.QSlider(self.centralwidget)
        self.FreqMinSlider.setMinimum(1)
        self.FreqMinSlider.setMaximum(50)
        self.FreqMinSlider.setProperty("value", 6)
        self.FreqMinSlider.setOrientation(QtCore.Qt.Horizontal)
        self.FreqMinSlider.setInvertedControls(False)
        self.FreqMinSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.FreqMinSlider.setTickInterval(10)
        self.FreqMinSlider.setObjectName("FreqMinSlider")
        self.verticalLayout.addWidget(self.FreqMinSlider)
        self.freqmaxLabel = QtWidgets.QLabel(self.centralwidget)
        self.freqmaxLabel.setObjectName("freqmaxLabel")
        self.verticalLayout.addWidget(self.freqmaxLabel)
        self.FreqMaxSlider = QtWidgets.QSlider(self.centralwidget)
        self.FreqMaxSlider.setMinimum(20)
        self.FreqMaxSlider.setMaximum(70)
        self.FreqMaxSlider.setProperty("value", 40)
        self.FreqMaxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.FreqMaxSlider.setInvertedControls(False)
        self.FreqMaxSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.FreqMaxSlider.setTickInterval(10)
        self.FreqMaxSlider.setObjectName("FreqMaxSlider")
        self.verticalLayout.addWidget(self.FreqMaxSlider)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.yMinLabel = QtWidgets.QLabel(self.centralwidget)
        self.yMinLabel.setObjectName("yMinLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.yMinLabel)
        self.yMinLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.yMinLineEdit.setObjectName("yMinLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.yMinLineEdit)
        self.yMaxLabel = QtWidgets.QLabel(self.centralwidget)
        self.yMaxLabel.setObjectName("yMaxLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.yMaxLabel)
        self.yMaxLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.yMaxLineEdit.setObjectName("yMaxLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.yMaxLineEdit)
        self.preSetLabel = QtWidgets.QLabel(self.centralwidget)
        self.preSetLabel.setObjectName("preSetLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.preSetLabel)
        self.preSetLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.preSetLineEdit.setObjectName("preSetLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.preSetLineEdit)
        self.afterSetLabel = QtWidgets.QLabel(self.centralwidget)
        self.afterSetLabel.setObjectName("afterSetLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.afterSetLabel)
        self.afterSetLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.afterSetLineEdit.setObjectName("afterSetLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.afterSetLineEdit)
        self.scaleLabel = QtWidgets.QLabel(self.centralwidget)
        self.scaleLabel.setObjectName("scaleLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.scaleLabel)
        self.scaleLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.scaleLineEdit.setObjectName("scaleLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.scaleLineEdit)
        self.textTypeLabel = QtWidgets.QLabel(self.centralwidget)
        self.textTypeLabel.setObjectName("textTypeLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.textTypeLabel)
        self.textTypeComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.textTypeComboBox.setObjectName("textTypeComboBox")
        self.textTypeComboBox.addItem("")
        self.textTypeComboBox.addItem("")
        self.textTypeComboBox.addItem("")
        self.textTypeComboBox.addItem("")
        self.textTypeComboBox.addItem("")
        self.textTypeComboBox.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.textTypeComboBox)
        self.oneDModelLabel = QtWidgets.QLabel(self.centralwidget)
        self.oneDModelLabel.setObjectName("oneDModelLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.oneDModelLabel)
        self.oneDModelComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.oneDModelComboBox.setObjectName("oneDModelComboBox")
        self.oneDModelComboBox.addItem("")
        self.oneDModelComboBox.addItem("")
        self.oneDModelComboBox.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.oneDModelComboBox)
        self.directionLabel = QtWidgets.QLabel(self.centralwidget)
        self.directionLabel.setObjectName("directionLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.directionLabel)
        self.directionComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.directionComboBox.setObjectName("directionComboBox")
        self.directionComboBox.addItem("")
        self.directionComboBox.addItem("")
        self.directionComboBox.addItem("")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.directionComboBox)
        self.alignedPhaseLabel = QtWidgets.QLabel(self.centralwidget)
        self.alignedPhaseLabel.setObjectName("alignedPhaseLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.alignedPhaseLabel)
        self.alignedPhaseComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.alignedPhaseComboBox.setObjectName("alignedPhaseComboBox")
        self.alignedPhaseComboBox.addItem("")
        self.alignedPhaseComboBox.addItem("")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.alignedPhaseComboBox)
        self.yaxisTypeLabel = QtWidgets.QLabel(self.centralwidget)
        self.yaxisTypeLabel.setObjectName("yaxisTypeLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.yaxisTypeLabel)
        self.yaxisTypeComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.yaxisTypeComboBox.setObjectName("yaxisTypeComboBox")
        self.yaxisTypeComboBox.addItem("")
        self.yaxisTypeComboBox.addItem("")
        self.yaxisTypeComboBox.addItem("")
        self.yaxisTypeComboBox.addItem("")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.yaxisTypeComboBox)
        self.modeLabel = QtWidgets.QLabel(self.centralwidget)
        self.modeLabel.setObjectName("modeLabel")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.modeLabel)
        self.modeComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.modeComboBox.setObjectName("modeComboBox")
        self.modeComboBox.addItem("")
        self.modeComboBox.addItem("")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.modeComboBox)
        self.eventLabel = QtWidgets.QLabel(self.centralwidget)
        self.eventLabel.setObjectName("eventLabel")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.eventLabel)
        self.eventComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.eventComboBox.setObjectName("eventComboBox")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.eventComboBox)
        self.stationLabel = QtWidgets.QLabel(self.centralwidget)
        self.stationLabel.setObjectName("stationLabel")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.stationLabel)
        self.stationComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.stationComboBox.setObjectName("stationComboBox")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.stationComboBox)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.directoryButton = QtWidgets.QPushButton(self.centralwidget)
        self.directoryButton.setObjectName("directoryButton")
        self.verticalLayout.addWidget(self.directoryButton)
        self.loadStationButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadStationButton.setCheckable(False)
        self.loadStationButton.setObjectName("loadStationButton")
        self.verticalLayout.addWidget(self.loadStationButton)
        self.loadCatalogButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadCatalogButton.setObjectName("loadCatalogButton")
        self.verticalLayout.addWidget(self.loadCatalogButton)
        self.plotButton = QtWidgets.QPushButton(self.centralwidget)
        self.plotButton.setObjectName("plotButton")
        self.verticalLayout.addWidget(self.plotButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.globalNormLabel.setText(_translate("MainWindow", "globalNorm"))
        self.freqminLabel.setText(_translate("MainWindow", "min frequency: 6"))
        self.freqmaxLabel.setText(_translate("MainWindow", "max frequency: 40"))
        self.yMinLabel.setText(_translate("MainWindow", "yMin"))
        self.yMinLineEdit.setText(_translate("MainWindow", "0"))
        self.yMaxLabel.setText(_translate("MainWindow", "yMax"))
        self.yMaxLineEdit.setText(_translate("MainWindow", "1000"))
        self.preSetLabel.setText(_translate("MainWindow", "preSet"))
        self.preSetLineEdit.setText(_translate("MainWindow", "60"))
        self.afterSetLabel.setText(_translate("MainWindow", "afterSet"))
        self.afterSetLineEdit.setText(_translate("MainWindow", "300"))
        self.scaleLabel.setText(_translate("MainWindow", "scale"))
        self.scaleLineEdit.setText(_translate("MainWindow", "1"))
        self.textTypeLabel.setText(_translate("MainWindow", "textType"))
        self.textTypeComboBox.setItemText(0, _translate("MainWindow", "None"))
        self.textTypeComboBox.setItemText(1, _translate("MainWindow", "Event ID"))
        self.textTypeComboBox.setItemText(2, _translate("MainWindow", "Depth"))
        self.textTypeComboBox.setItemText(3, _translate("MainWindow", "Azimuth"))
        self.textTypeComboBox.setItemText(4, _translate("MainWindow", "Epicenter Distance"))
        self.textTypeComboBox.setItemText(5, _translate("MainWindow", "Euclidean Distance"))
        self.oneDModelLabel.setText(_translate("MainWindow", "oneDModel"))
        self.oneDModelComboBox.setItemText(0, _translate("MainWindow", "ak135"))
        self.oneDModelComboBox.setItemText(1, _translate("MainWindow", "iasp91"))
        self.oneDModelComboBox.setItemText(2, _translate("MainWindow", "prem"))
        self.directionLabel.setText(_translate("MainWindow", "direction"))
        self.directionComboBox.setItemText(0, _translate("MainWindow", "Vertical"))
        self.directionComboBox.setItemText(1, _translate("MainWindow", "Radial"))
        self.directionComboBox.setItemText(2, _translate("MainWindow", "Tangential"))
        self.alignedPhaseLabel.setText(_translate("MainWindow", "alignedPhase"))
        self.alignedPhaseComboBox.setItemText(0, _translate("MainWindow", "s/S"))
        self.alignedPhaseComboBox.setItemText(1, _translate("MainWindow", "p/P"))
        self.yaxisTypeLabel.setText(_translate("MainWindow", "yaxisType"))
        self.yaxisTypeComboBox.setItemText(0, _translate("MainWindow", "Epicenter Distance"))
        self.yaxisTypeComboBox.setItemText(1, _translate("MainWindow", "Euclidean Distance"))
        self.yaxisTypeComboBox.setItemText(2, _translate("MainWindow", "Depth"))
        self.yaxisTypeComboBox.setItemText(3, _translate("MainWindow", "Azimuth"))
        self.modeLabel.setText(_translate("MainWindow", "mode"))
        self.modeComboBox.setItemText(0, _translate("MainWindow", "Event"))
        self.modeComboBox.setItemText(1, _translate("MainWindow", "Station"))
        self.eventLabel.setText(_translate("MainWindow", "Event"))
        self.stationLabel.setText(_translate("MainWindow", "Station"))
        self.directoryButton.setText(_translate("MainWindow", "Load waveform directory"))
        self.loadStationButton.setText(_translate("MainWindow", "Load Station File"))
        self.loadCatalogButton.setText(_translate("MainWindow", "Load Event Catalog File"))
        self.plotButton.setText(_translate("MainWindow", "Plot"))

from seisPlotPy.mplwidget import MplWidget
